export const feynmanQuotes = [
  "I would rather have questions that can't be answered than answers that can't be questioned.",
  "The first principle is that you must not fool yourself—and you are the easiest person to fool.",
  "We are lucky to be alive. We should enjoy it.",
  "I have a friend who's an artist... but I see a deeper beauty.",
  "Nature uses only the longest threads to weave her patterns, so that each small piece of her fabric reveals the organization of the entire tapestry.",
  "Physics is imagination in a straightjacket.",
  "I was born not knowing and have had only a little time to change that here and there.",
  "For a successful technology, reality must take precedence over public relations, for nature cannot be fooled.",
  "Study hard what interests you the most in the most original manner possible.",
  "What I cannot create, I do not understand.",
  "The idea is to try to give all of the information to help others to judge the value of your contribution; not just the information that leads to judgment in one particular direction or another.",
  "You can know the name of a bird in all the languages of the world, but when you're finished, you'll know absolutely nothing whatever about the bird. So let's look at the bird and see what it's doing — that's what counts.",
  "The highest forms of understanding we can achieve are those which are clean and simple and can be stated in a few words.",
  "I'm smart enough to know that I'm dumb.",
  "Fall in love with some activity, and do it! Nobody ever figures out what life is all about, and it doesn't matter.",
  "The wonder is that we can understand at all.",
  "If you thought that science was certain - well, that is just an error on your part.",
  "The truth always turns out to be simpler than you thought.",
  "I don't have any special talent. I am just passionately curious.",
  "The joy of learning is the most beautiful thing in the world.",
  "I'm curious about everything.",
  "I'm not a pessimist. I'm a realist.",
  
];
